apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP
  #type: NodePort
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
